[production]
144.31.213.64 ansible_user=root

[all:vars]
ansible_connection=ssh
# Для избежания проблем с проверкой ключа хоста при первом подключении
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
